### ISSUE TITLE
Is the file on the download page correct?

### ISSUE THREAD

**Issue by quade-ksp** [JonnyOThan/kOSPropMonitor#5]
Here's what I'm seeing.
<img width="916" alt="Screen Shot 2020-01-22 at 11 25 53 AM" src="https://user-images.githubusercontent.com/35043614/72927094-6e6fa800-3d0a-11ea-8958-f78b1cc6d84e.png">
and when I download it this is what I get.
<img width="672" alt="Screen Shot 2020-01-22 at 11 27 16 AM" src="https://user-images.githubusercontent.com/35043614/72927123-7a5b6a00-3d0a-11ea-8264-68b05051a4a2.png">

**Comment by meh1s** [comment]
It looks like MacOS doesn't like the way these files are in the zip. Looks like windows \ isn't recognised as / in mac. I fixed this problem with creating this structure manually - just create folders like they are meant to be.

**Comment by melvspace** [comment]
If familiar to terminal, extract to some folder, terminal in there and
`rm -d */; for file in *\\*; do target="${file//\\//}"; mkdir -p "${target%/*}"; mv -v "$file" "$target"; done`

Wonder why still nobody fixed archive

**Comment by JonnyOThan** [comment]
Fixed now!
